name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}


    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check formatting
      run: npm run format:check


    - name: Build lib
      run: npm run build:lib

    - name: Build CLI
      run: npm run build:cli

    - name: Run tests
      run: npm test
